---
- name: VMware VM Create plabook with parameters
  hosts: all
  gather_facts: no
  connection: local

  tasks:
  - name: Create VM with vmware_guest module
    vmware_guest:
      folder: RedHat
      datacenter: Datacenter1
      name: "{{ vm_name }}"
      state: poweredon
      template: rhel8_template
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: 2
      networks:
      - name: DSwitch-VM Network
      customization:
        hostname: "{{ vm_name }}.example.local"
      wait_for_ip_address: true
      cluster: Cluster1
      datastore: compelent
    delegate_to: localhost
    register: deploy

  - name: Szybki debug
    debug:
      var: deploy.instance.hw_eth0.ipaddresses[0]

  # - name: Email
  #   mail:
  #     subject: "Maszyna {{ vm_name }} jest gotowa !"
  #     body: "Twoja aplikacja dostępna jest pod adresem: https://{{ APP_NAME }}.apps.ocp1.example.lab"
  #     from: "Automation robot - noreply"
  #     to:
  #       - Artur Poczekalewicz <artur@poczekalewicz.net>