---
- name: VMware VM Delete plabook
  hosts: all
  gather_facts: no
  connection: local

  tasks:
  - name: Remove a virtual machine from inventory
    vmware_guest:
      name: "{{ vm_name }}"
      state: absent
    delegate_to: localhost