---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress

  post_tasks:
  - name: Register app url
    set_stats:
      data:
        app_url: "{{ ansible_host }}"