---
- name: Create container app
  hosts: all
  gather_facts: no
  connection: local

  tasks:

  - name: Create application
    k8s:
      state: present
      template:
        path: 'kubernetes_objects.yaml'
