---
- name: Create container app
  hosts: all
  gather_facts: no
  connection: local

  tasks:

  - name: Copy file
    template:
      src: k8s_objects.j2
      dest: /tmp/all.yaml

  - name: Create application
    k8s:
      state: present
      definition: "{{ lookup('template', '/tmp/all.yaml') }}"

