---
- name: Create container app
  hosts: all
  gather_facts: no

- name: Create application
  k8s:
    state: present
    template:
      path: 'kubernetes_objects.yaml'
      variable_start_string: '{{'
      variable_end_string: '}}'
