- name: k8s
  hosts: all
  tasks:

  - name: Get a list of all pods from any namespace
    community.kubernetes.k8s_info:
      kind: Pod
    register: pod_list

  - name: print info
    debug:
      var: pod_list

