---
- name: RETRIEVE WORKER NODE DETAILS FROM KUBERNETES NODE
  hosts: localhost
  gather_facts: no

  tasks:
  - name: GET WORKER NODE DETAILS
    k8s_info:
      kind: Node
      namespace: default
    register: zmienna

  - name: print info
    debug:
      msg: "Info: {{ zmienna }}"

